# Generated by Django 5.0.3 on 2024-06-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('lesson_number', models.CharField(max_length=1000)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
